version: "3.9"

services:

  phonebook:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:h2:mem:phonebook
      - spring.datasource.initialization-mode=always
