apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: phonebook-deployment
  name: phonebook
spec:
  selector:
    matchLabels:
      name: phonebook-deployment    
  template:   
    metadata:   
      labels:   
        name: phonebook-deployment
    spec:   
      containers:   
      - name: phonebook   
        image: phonebook:latest
        imagePullPolicy: Never
        ports:   
        - containerPort: 8080
